@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype polyline

abstract class CollisionStrategy {
+ //handle(movElem: Movable, collElem: Collidable) : boolean//
}
class BlockCollision {}
class NullCollision {}
class SkaneAttackCollision {}

interface Controller {
+ update(room: Room)
}
interface PlayerController {
+ setEvent(event: EVENT)
+ handleEvent(event: EVENT, room: Room)
}
class CollisionHandler {}
class EnemyController {}
class MovableController {}
class SkaneController {}

BlockCollision -up-^ CollisionStrategy
NullCollision -up-^ CollisionStrategy
SkaneAttackCollision -up-^ CollisionStrategy

MovableController .up.^ Controller
SkaneController .up.^ PlayerController
SkaneController -up-^ MovableController
EnemyController -up-^ MovableController

MovableController -right-> CollisionHandler
CollisionHandler "1" -right-> "*" CollisionStrategy

@enduml
