@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam shadowing false

/' Behaviours '/

interface Agressive {
  + getAtk() : int
  + setAtk(atk)
}
interface Collidable {
  + getCollider() : Collider
  + collidesWith(colidee) : boolean
  + shadowStep(position) : Position
}
interface Mortal {
  + getHp() : int
  + setHp(hp)
  + takeDamage(dmg)
  + isAlive() : boolean
}
interface Movable {
  + getMovCounter() : int
  + setMovCounter(numTicks)
  + tickMovCounter()
  + setMoveStrat(moveStrat)
  + genMoves(model, element) : List<Position>
}

class AgressiveBehaviour {}
class CollidableBehaviour {}
class ImmortalBehaviour {}
class ImovableBehaviour {}
class MortalBehaviour {}
class MovableBehaviour {}
class NotCollidableBehaviour {}
class PassiveBehaviour {}

abstract class Element {}

/' Elements '/

package "Game Elements" #BBBBEE {
  class Civilian {}
  class Laser {}
  class MeleeGuy {}
  class Wall {}
  class RangedGuy {}
  class Scent {}
  class Skane {}
  class SkaneBody {}
}

/' Connections '/

AgressiveBehaviour .down.^ Agressive
CollidableBehaviour .down.^ Collidable
ImmortalBehaviour .down.^ Mortal
ImovableBehaviour .down.^ Movable
MortalBehaviour .down.^ Mortal
MovableBehaviour .down.^ Movable
NotCollidableBehaviour .down.^ Collidable
PassiveBehaviour .down.^ Agressive

Element -up-> Agressive
Element -up-> Collidable
Element -up-> Mortal
Element -up-> Movable

Element .up.^ Agressive
Element .up.^ Collidable
Element .up.^ Mortal
Element .up.^ Movable

Civilian --up-^ Element
Laser --up-^ Element
MeleeGuy --up-^ Element
Wall --up-^ Element
RangedGuy --up-^ Element
Scent --up-^ Element
Skane --up-^ Element
SkaneBody --up-^ Element

@enduml
