@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam shadowing false

/' Behaviour '/

interface Agressive {
+ setAtkStrat(AttackStrategy)
+ getAtkStrat() : AttackStrategy
+ attack(Room, me: Element, target: Element) : boolean
}

abstract class Element {
+ attack(Room, target: Element) : boolean
}

class AgressiveBehaviour {
- attackStrat: AttackStrategy
}
class PassiveBehaviour {}

class Laser {}
class MeleeGuy {}
class RangedGuy {}

/' Attack strats '/

interface AttackStrategy {
+ attack(Room, me: Element, target: Element) : boolean
}

class LaserAtkStrat {}
class MeleeAtkStrat {}
class RangedGuyAtkStrat {}

/' Connections '/

AgressiveBehaviour .down.^ Agressive
PassiveBehaviour .down.^ Agressive

Element -up-> Agressive
Element .up.^ Agressive

Laser -up-^ Element
MeleeGuy -up-^ Element
RangedGuy -up-^ Element

LaserAtkStrat .up.^ AttackStrategy
MeleeAtkStrat .up.^ AttackStrategy
RangedGuyAtkStrat .up.^ AttackStrategy

AgressiveBehaviour -left-> AttackStrategy

@enduml
