@startuml

hide empty members
skinparam shadowing false
skinparam linetype polyline

abstract class CollisionStrategy {}
class BlockCollision {}
class NullCollision {}
class SkaneAttackCollision {}

interface Controller {}
interface PlayerController {}
class CollisionHandler {}
class EnemyController {}
class MovableController {}
class SkaneController {}

BlockCollision -up-^ CollisionStrategy
NullCollision -up-^ CollisionStrategy
SkaneAttackCollision -up-^ CollisionStrategy

MovableController .up.^ Controller
SkaneController .up.^ PlayerController
SkaneController -up-^ MovableController
EnemyController -up-^ MovableController

MovableController -right-> CollisionHandler
CollisionHandler "1" -right-> "*" CollisionStrategy

@enduml
