@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam shadowing false

interface Observer {}

abstract class Collider {
- position: Position
+ // colliderWith(Collider) : boolean //
+ changed(Position)
}

class CompositeCollider {}
class RectangleCollider {}

Collider .up.^ Observer
CompositeCollider -up-^ Collider
RectangleCollider -up-^ Collider

@enduml
