@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam shadowing false

interface Observer<T> {
    + // changed(T) : void //
}

abstract class Collider {
    - position: Position
    + // colliderWith(Collider) : boolean //
    + changed(Position)
}

class CompositeCollider {}
class RectangleCollider {}

interface Observable<T> {
    + // addObserver(Observer<T>) : void //
    + // removeObserver(Observer<T>) : void //
    + // notifyObserver(Observer<T>) : void //
}

interface Collidable {
    + // getCollider() : Collider //
    + // colliderWith(Collidable) : boolean //
}


abstract class Element {}

Collider "Position".up.^ Observer
CompositeCollider -up-^ Collider
RectangleCollider -up-^ Collider

Collidable "Position"-up-^ Observable
Element "Position".up.^ Collidable
Element -right-> Collider

@enduml
