@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam shadowing false

interface Agressive {
  + getAtk() : int
  + setAtk(atk)
}
interface Collidable {
  + getCollider() : Collider
  + collidesWith(colidee) : boolean
  + shadowStep(position) : Position
}
interface Mortal {
  + getHp() : int
  + setHp(hp)
  + takeDamage(dmg)
  + isAlive() : boolean
}
interface Movable {
  + getMovCounter() : int
  + setMovCounter(numTicks)
  + tickMovCounter()
  + setMoveStrat(moveStrat)
  + genMoves(org.g73.skanedweller.model, element) : List<Position>
}

class AgressiveBehaviour {}
class CollidableBehaviour {}
class ImmortalBehaviour {}
class ImovableBehaviour {}
class MortalBehaviour {}
class MovableBehaviour {}
class NotCollidableBehaviour {}

abstract class Element {}

class Civilian {}
class MeleeGuy {}
class Wall {}

class Scent {}
class Skane {}
class SkaneBody {}

AgressiveBehaviour .up.^ Agressive
CollidableBehaviour .up.^ Collidable
ImmortalBehaviour .up.^ Mortal
ImovableBehaviour .up.^ Movable
MortalBehaviour .up.^ Mortal
MovableBehaviour .up.^ Movable
NotCollidableBehaviour .up.^ Collidable

Element -up-> AgressiveBehaviour
Element -up-> CollidableBehaviour
Element -up-> ImmortalBehaviour
Element -up-> ImovableBehaviour
Element -up-> MortalBehaviour
Element -up-> MovableBehaviour
Element -up-> NotCollidableBehaviour

Civilian -up-^ Element
MeleeGuy -up-^ Element
Wall -up-^ Element
Scent -up-^ Element
Skane -up-^ Element
SkaneBody -up-^ Element

@enduml

