@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam shadowing false

interface Movable {
  + setMoveStrat(moveStrat)
  + genMoves(room, element) : List<Position>
}

interface MoveStrategy {
+ genMoves(Room, Element)
}

abstract class Element {
- moveStrategy
+ executeStrategy(Room) : List<Position>
}

class MeleeMoveStrat {}
class ScaredMoveStrat {}
class ImovableBehaviour {}
class MovableBehaviour {}
class Civilian {}
class MeleeGuy {}

ImovableBehaviour .up.^ Movable
MovableBehaviour .up.^ Movable

Element -up-> ImovableBehaviour
Element -up-> MovableBehaviour

Civilian -up-^ Element
MeleeGuy -up-^ Element

MeleeMoveStrat .up.^ MoveStrategy
ScaredMoveStrat .up.^ MoveStrategy

MovableBehaviour -left-> MoveStrategy 

@enduml

