@startuml

hide empty members

class Room {}

interface GraphicsDrawer {}
class Drawer {}
class Gui {}

interface Controller {}
interface PlayerController {}
abstract class MovableController {}
class GameController {}
class EnemyController {}
class SkaneController {}

PlayerController -up-^ Controller
GameController .up.^ Controller
MovableController .up.^ Controller

EnemyController -up-^ MovableController
SkaneController -up-^ MovableController 
SkaneController .up.^ PlayerController

Gui -up-> GraphicsDrawer
Drawer ..^ GraphicsDrawer 

Controller --> Room
Gui --> Room

@enduml

