@startuml

hide empty members
skinparam shadowing false
skinparam linetype polyline

package "Model" #EEDDDD {
  class Room {}
}

package "View" #DDEEDD {
  interface RoomDrawer {}
  class CivieView {}
  class MeleeGuyView {}
  class RoomView {}
  class SkaneView {}
  class WallView {}
  class Drawer {}
  class Gui {}
}

package "Controller" #DDDDEE {
  class CollisionHandler {}
  interface Controller {}
  class EnemyController {}
  class GameController {}
  abstract class MovableController {}
  interface PlayerController {}
  class SkaneController {}
}

PlayerController -up-^ Controller
MovableController .up.^ Controller
MovableController -down-> CollisionHandler
GameController .up.^ Controller
GameController -down-> SkaneController
GameController -down-> EnemyController

EnemyController --^ MovableController
SkaneController --^ MovableController 
SkaneController .up.^ PlayerController

Drawer -up-> CivieView
Drawer -up-> MeleeGuyView
Drawer -up-> RoomView
Drawer -up-> SkaneView
Drawer -up-> WallView
Drawer .down.^ RoomDrawer 
Gui -right-> RoomDrawer
Gui -down-> Room

GameController ---> Room
GameController --right-> Gui

@enduml

