@startuml

hide empty members
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam shadowing false

Class TerminalResizeHandler {
+ hasResized() : Boolean
+ getLastKnownSize() : TerminalSize
+ onResized(terminal: Terminal, newSize: TerminalSize)
}
Interface TerminalResizeListener {}
Interface Terminal {}
Class Gui {}

Gui -up-^ TerminalResizeListener
TerminalResizeHandler .down.^ TerminalResizeListener
Terminal -left-> TerminalResizeListener

@enduml

